name = "§o§l§aNewb Reverie"
version = [1, 1, 1]
min_supported_mc_version = [1, 21, 130]
description = '''
§c%w
§7- §fAdding clarity to MCBE graphics.
%v
§3https://KianSantan88.github.io/newb-wondr/
''' # %w = patch warning, %v = version
authors = ["raden1/ardrafflesia", "devendrn"]
url = "https://KianSantan88.github.io/newb-wondr/"
uuid = "25953af5-e9a8-49d5-b2a4-b21a681fef2b" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "HIGH_REALISTIC_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§4High (realistic clouds)
- §oRealistic-ish clouds and the usual.
'''

[[subpack]]
define = "HIGH_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§4High (rounded clouds)
- §oMultilayer 16 steps Rounded Clouds
- §oFolliage waves
- §oGlow leaks and Shimmer
'''

[[subpack]]
define = "HIGH_ROUNDED_CLOUDS_NO_AURORA"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§4High (rounded clouds, aurora disabled)
- §oMultilayer 16 steps Rounded Clouds
- §oNo Aurora
- §oFolliage waves
- §oGlow leaks and Shimmer
'''

[[subpack]]
define = "HIGH_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§4High (box clouds)
- §oMultilayer Box Clouds
- §oFolliage waves
- §oGlow leaks and Shimmer
'''


[[subpack]]
define = "MEDIUM_REALISTIC_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§eMedium (realistic clouds)
- §oRealistic-ish clouds
- §oNo Folliage waves
- §oNo Glow and Shimmer
'''


[[subpack]]
define = "MEDIUM_BOX_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§eMedium (box clouds)
- §oBox Clouds
- §oNo Folliage Waves
- §oNo Glow and Shimmer
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§eMedium (rounded clouds)
- §oRounded Clouds
- §oNo Folliage Waves
- §oNo Glow and Shimmer
'''

[[subpack]]
define = "MEDIUM_ROUNDED_CLOUDS_NO_AURORA"
materials = ["Clouds", "RenderChunk", "Sky", "EndSky", "Stars"]
description = '''
§eMedium (rounded clouds, aurora disabled)
- §oRounded Clouds
- §oNo Aurora
- §oNo Folliage Waves 
- §oNo Glow and Shimmer
'''

[[subpack]]
define = "LITE"
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
description = '''
§aLite (soft clouds)
- §oMany effects disabled. A bit lighter!
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''